// Fixed TVM operand/result signatures ported from decompiler/ir.py.
export const primitiveSignatures: Record<string, [string[], string[]]> = {
  RANDU256: [[], ['int']],
  SETGASLIMIT: [['int'], []],
  SETRAND: [['int'], []],
  BREMBITS: [['builder'], ['int']],
  BREMREFS: [['builder'], ['int']],
  PLDREFVAR: [['slice', 'int'], ['cell']],
  DIVC: [['int', 'int'], ['int']],
  DIVR: [['int', 'int'], ['int']],
  DICTUADD: [
    ['slice', 'int', 'cell', 'int'],
    ['cell', 'int'],
  ],
  DICTIADD: [
    ['slice', 'int', 'cell', 'int'],
    ['cell', 'int'],
  ],
  SHA256U: [['slice'], ['int']],
  SDSUBSTR: [['slice', 'int', 'int'], ['slice']],
  INCOMINGVALUE: [[], ['[int, cell]']],
  RIST255_VALIDATE: [['int'], []],
  RIST255_MULBASE: [['int'], ['int']],
  STUX: [['int', 'builder', 'int'], ['builder']],
  STIX: [['int', 'builder', 'int'], ['builder']],
  DIVMOD: [
    ['int', 'int'],
    ['int', 'int'],
  ],
  CHKSIGNS: [['slice', 'slice', 'int'], ['int']],
  DICTISETGETOPTREF: [
    ['cell', 'int', 'cell', 'int'],
    ['cell', 'cell'],
  ],
  DICTUSETGETOPTREF: [
    ['cell', 'int', 'cell', 'int'],
    ['cell', 'cell'],
  ],
  BBITS: [['builder'], ['int']],
  BREFS: [['builder'], ['int']],
  SETLIBCODE: [['cell', 'int'], []],
  CHANGELIB: [['int', 'int'], []],
  DICTUSET: [['slice', 'int', 'cell', 'int'], ['cell']],
  DICTISET: [['slice', 'int', 'cell', 'int'], ['cell']],
  RAWRESERVE: [['int', 'int'], []],
  SETCODE: [['cell'], []],
  MIN: [['int', 'int'], ['int']],
  MAX: [['int', 'int'], ['int']],
  SDEPTH: [['slice'], ['int']],
  CDEPTH: [['cell'], ['int']],
  RAND: [['int'], ['int']],
  ADDRAND: [['int'], []],
  CDATASIZE: [
    ['cell', 'int'],
    ['int', 'int', 'int'],
  ],
  DICTIGETOPTREF: [['int', 'cell', 'int'], ['cell']],
  DICTUGETOPTREF: [['int', 'cell', 'int'], ['cell']],
  DICTUSETB: [['builder', 'int', 'cell', 'int'], ['cell']],
  DICTISETB: [['builder', 'int', 'cell', 'int'], ['cell']],
  DICTSETB: [['builder', 'slice', 'cell', 'int'], ['cell']],
  DICTADDB: [
    ['builder', 'slice', 'cell', 'int'],
    ['cell', 'int'],
  ],
  DICTDEL: [
    ['slice', 'cell', 'int'],
    ['cell', 'int'],
  ],
  DICTISETREF: [['cell', 'int', 'cell', 'int'], ['cell']],
  STZEROES: [['builder', 'int'], ['builder']],
  THROWANYIF: [['int', 'int'], []],
  THROWANYIFNOT: [['int', 'int'], []],
  ABS: [['int'], ['int']],
  POW2: [['int'], ['int']],
  SREMPTY: [['slice'], ['int']],
  SDCNTLEAD0: [['slice'], ['int']],
  PLDDICT: [['slice'], ['cell']],
  XCTOS: [['cell'], ['slice', 'int']],
  HASHSU: [['slice'], ['int']],
  CHKSIGNU: [['int', 'slice', 'int'], ['int']],
  SDCNTTRAIL0: [['slice'], ['int']],
  SDCNTTRAIL1: [['slice'], ['int']],
  DICTUADDB: [
    ['builder', 'int', 'cell', 'int'],
    ['cell', 'int'],
  ],
  SDATASIZE: [
    ['slice', 'int'],
    ['int', 'int', 'int'],
  ],
  STB: [['builder', 'builder'], ['builder']],
  STSLICE: [['slice', 'builder'], ['builder']],
  LDREFRTOS: [['slice'], ['slice', 'slice']],
  REWRITEVARADDR: [['slice'], ['int', 'slice']],
  SDPFXREV: [['slice', 'slice'], ['int']],
  SDPPFXREV: [['slice', 'slice'], ['int']],
  CTOS: [['cell'], ['slice']],
  NEWC: [[], ['builder']],
  ENDC: [['builder'], ['cell']],
  SEMPTY: [['slice'], ['int']],
  SDEMPTY: [['slice'], ['int']],
  SREFS: [['slice'], ['int']],
  SBITS: [['slice'], ['int']],
  LDREF: [['slice'], ['cell', 'slice']],
  STREF: [['cell', 'builder'], ['builder']],
  STSLICER: [['builder', 'slice'], ['builder']],
  REWRITESTDADDR: [['slice'], ['int', 'int']],
  LDMSGADDR: [['slice'], ['slice', 'slice']],
  LDGRAMS: [['slice'], ['int', 'slice']],
  STGRAMS: [['builder', 'int'], ['builder']],
  LDDICT: [['slice'], ['cell', 'slice']],
  STDICT: [['cell', 'builder'], ['builder']],
  SDSKIPFIRST: [['slice', 'int'], ['slice']],
  SDEQ: [['slice', 'slice'], ['int']],
  STBR: [['builder', 'builder'], ['builder']],
  SENDRAWMSG: [['cell', 'int'], []],
  MULDIV: [['int', 'int', 'int'], ['int']],
  DICTUSETREF: [['cell', 'int', 'cell', 'int'], ['cell']],
  DICTUDEL: [
    ['int', 'cell', 'int'],
    ['cell', 'int'],
  ],
  DICTIDEL: [
    ['int', 'cell', 'int'],
    ['cell', 'int'],
  ],
  UBITSIZE: [['int'], ['int']],
  BITSIZE: [['int'], ['int']],
  CONFIGOPTPARAM: [['int'], ['cell']],
};
